### ISSUE TITLE
can not find dependent library

### ISSUE THREAD

**Issue by Francis0** [opsun/MT4Wrapper#2]
Hey opsun,

我們工作中也剛在使用MT4 Manager API，我們總是提示 找不到 dependent library，是否可以請教下？
是否能加您的QQ或者wechat請教下？我的wechat: anyevo， QQ:1563275，希望能請教您

Best Regards
Francis
2016/09/01

**Comment by opsun** [comment]
找不到 dependent library ,是因为 System.loadLibrary 没有找到dll文件吧。需要把dll文件放在classpath下，或者复制到 %windir%/system32 目录下

**Comment by Francis0** [comment]
很高兴您能回复。
我们确实都在system32和classpath放过了，不知道哪里出了错误

是否方便联系我，我还有一些其他的需求，虽然我们也有成熟的开发团队，但在这方面我们是新手，如果您有时间帮忙，我们可以付赞助费用

**Comment by opsun** [comment]
dll是需要两个mtmanapi.dll 和MT4Warpper.dll,能把错误信息贴出来吗?

**Comment by Francis0** [comment]
Exception in thread "main" java.lang.UnsatisfiedLinkError: D:\GIT\MT4Warpper\mt4-manager-api\src\test\java\com\opsunv\mt4\api\MT4Warpper.dll: Can't find dependent libraries at java.lang.ClassLoader$NativeLibrary.load(Native Method) at java.lang.ClassLoader.loadLibrary0(Unknown Source) at java.lang.ClassLoader.loadLibrary(Unknown Source) at java.lang.Runtime.load0(Unknown Source) at java.lang.System.load(Unknown Source) at com.opsunv.mt4.api.MT4ManagerAPI.<clinit>(MT4ManagerAPI.java:84) at com.opsunv.mt4.api.Test.main(Test.java:9) 

DLL包确认已经添加，系统环境windows10 32位操作系统 AMD X64架构处理器

DLL包路径 System32 项目根目录 类所在目录都已经添加

MT4warpper能够调用到，但是mtmanapi.dll调取不到

**Comment by opsun** [comment]
Fixed
