### ISSUE TITLE
你好，感谢分享您的项目，但是运行有错误：java.lang.UnsatisfiedLinkError:Can't find dependent libraries

### ISSUE THREAD

**Issue by Duhonghao** [opsun/MT4Wrapper#3]
`Exception in thread "main" java.lang.UnsatisfiedLinkError: D:\GIT\MT4Warpper\mt4-manager-api\src\test\java\com\opsunv\mt4\api\MT4Warpper.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at com.opsunv.mt4.api.MT4ManagerAPI.<clinit>(MT4ManagerAPI.java:84)
	at com.opsunv.mt4.api.Test.main(Test.java:9)
`

DLL包确认已经添加，系统环境windows10 32位操作系统 AMD X64架构处理器

DLL包路径  System32  项目根目录   类所在目录都已经添加

MT4warpper能够调用到，但是mtmanapi.dll调取不到

**Comment by opsun** [comment]
Fxied
